# Generated by Django 4.2.29 on 2026-04-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_ensure_user_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='data_privacy_consent',
            field=models.BooleanField(default=False),
        ),
    ]
