# Generated by Django 4.2.29 on 2026-04-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_data_privacy_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'System Admin (DILG)'), ('BARANGAY', 'Barangay Admin'), ('BARANGAY_STAFF', 'Barangay Staff'), ('RESIDENT', 'Resident')], default='RESIDENT', max_length=20),
        ),
    ]
