--
-- PostgreSQL database dump
--

\restrict Ogcpp37LHZ5mZCI8m43oufdXdmkgnOyxtea81HVH5lUWF2uMH9Wm7leiWXXmTNc

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

-- Started on 2026-05-01 13:02:47

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 2 (class 3079 OID 16389)
-- Name: postgis; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;


--
-- TOC entry 6289 (class 0 OID 0)
-- Dependencies: 2
-- Name: EXTENSION postgis; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION postgis IS 'PostGIS geometry and geography spatial types and functions';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 232 (class 1259 OID 17516)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 17515)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 17526)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 17525)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 17506)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 17505)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 273 (class 1259 OID 18058)
-- Name: barangay_services_issueddocument; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.barangay_services_issueddocument (
    id bigint NOT NULL,
    document_type character varying(50) NOT NULL,
    document_number character varying(50) NOT NULL,
    purpose text NOT NULL,
    issued_at timestamp with time zone NOT NULL,
    is_paid boolean NOT NULL,
    barangay_id bigint NOT NULL,
    issued_by_id bigint,
    resident_id bigint NOT NULL
);


ALTER TABLE public.barangay_services_issueddocument OWNER TO postgres;

--
-- TOC entry 272 (class 1259 OID 18057)
-- Name: barangay_services_issueddocument_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.barangay_services_issueddocument ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.barangay_services_issueddocument_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 277 (class 1259 OID 18090)
-- Name: barangay_services_receipt; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.barangay_services_receipt (
    id bigint NOT NULL,
    receipt_number character varying(50) NOT NULL,
    amount numeric(10,2) NOT NULL,
    tax_fee numeric(10,2) NOT NULL,
    total_amount numeric(10,2) NOT NULL,
    payment_date timestamp with time zone NOT NULL,
    issued_document_id bigint NOT NULL,
    processed_by_id bigint
);


ALTER TABLE public.barangay_services_receipt OWNER TO postgres;

--
-- TOC entry 276 (class 1259 OID 18089)
-- Name: barangay_services_receipt_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.barangay_services_receipt ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.barangay_services_receipt_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 275 (class 1259 OID 18076)
-- Name: barangay_services_transactionlog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.barangay_services_transactionlog (
    id bigint NOT NULL,
    action character varying(20) NOT NULL,
    model_name character varying(100) NOT NULL,
    object_id integer,
    details text NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    ip_address inet,
    user_id bigint,
    CONSTRAINT barangay_services_transactionlog_object_id_check CHECK ((object_id >= 0))
);


ALTER TABLE public.barangay_services_transactionlog OWNER TO postgres;

--
-- TOC entry 274 (class 1259 OID 18075)
-- Name: barangay_services_transactionlog_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.barangay_services_transactionlog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.barangay_services_transactionlog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 242 (class 1259 OID 17631)
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 17630)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 17494)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 17493)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 17480)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 17477)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 251 (class 1259 OID 17725)
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 17658)
-- Name: gis_mapping_disasterpronearea; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.gis_mapping_disasterpronearea (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    type character varying(50) NOT NULL,
    boundary public.geometry(Polygon,4326) NOT NULL,
    risk_level integer NOT NULL,
    barangay_ref_id bigint
);


ALTER TABLE public.gis_mapping_disasterpronearea OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 17657)
-- Name: gis_mapping_disasterpronearea_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.gis_mapping_disasterpronearea ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gis_mapping_disasterpronearea_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 269 (class 1259 OID 17961)
-- Name: gis_mapping_evacuationsite; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.gis_mapping_evacuationsite (
    id bigint NOT NULL,
    name character varying(150) NOT NULL,
    location public.geometry(Point,4326) NOT NULL,
    capacity integer,
    barangay_id bigint NOT NULL,
    CONSTRAINT gis_mapping_evacuationsite_capacity_check CHECK ((capacity >= 0))
);


ALTER TABLE public.gis_mapping_evacuationsite OWNER TO postgres;

--
-- TOC entry 268 (class 1259 OID 17960)
-- Name: gis_mapping_evacuationsite_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.gis_mapping_evacuationsite ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gis_mapping_evacuationsite_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 17671)
-- Name: gis_mapping_infrastructure; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.gis_mapping_infrastructure (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    type character varying(50) NOT NULL,
    location public.geometry(Point,4326) NOT NULL,
    barangay character varying(100),
    barangay_ref_id bigint
);


ALTER TABLE public.gis_mapping_infrastructure OWNER TO postgres;

--
-- TOC entry 245 (class 1259 OID 17670)
-- Name: gis_mapping_infrastructure_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.gis_mapping_infrastructure ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gis_mapping_infrastructure_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 255 (class 1259 OID 17762)
-- Name: residents_announcement; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.residents_announcement (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    content text NOT NULL,
    barangay character varying(100),
    is_global boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    created_by_id bigint,
    barangay_id bigint,
    end_date date,
    start_date date
);


ALTER TABLE public.residents_announcement OWNER TO postgres;

--
-- TOC entry 254 (class 1259 OID 17761)
-- Name: residents_announcement_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.residents_announcement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.residents_announcement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 259 (class 1259 OID 17812)
-- Name: residents_barangay; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.residents_barangay (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    municipality character varying(100) NOT NULL,
    email character varying(254) NOT NULL,
    captain_name character varying(100) NOT NULL,
    is_approved boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    admin_user_id bigint,
    boundary public.geometry(Polygon,4326),
    is_active boolean NOT NULL,
    contact_number character varying(20)
);


ALTER TABLE public.residents_barangay OWNER TO postgres;

--
-- TOC entry 258 (class 1259 OID 17811)
-- Name: residents_barangay_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.residents_barangay ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.residents_barangay_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 253 (class 1259 OID 17746)
-- Name: residents_barangayservice; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.residents_barangayservice (
    id bigint NOT NULL,
    service_type character varying(100) NOT NULL,
    description text NOT NULL,
    status character varying(20) NOT NULL,
    barangay character varying(100) NOT NULL,
    requested_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    resident_id bigint NOT NULL
);


ALTER TABLE public.residents_barangayservice OWNER TO postgres;

--
-- TOC entry 252 (class 1259 OID 17745)
-- Name: residents_barangayservice_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.residents_barangayservice ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.residents_barangayservice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 248 (class 1259 OID 17686)
-- Name: residents_household; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.residents_household (
    id bigint NOT NULL,
    household_number character varying(50) NOT NULL,
    address text NOT NULL,
    location public.geometry(Point,4326),
    barangay character varying(100),
    created_at timestamp with time zone NOT NULL,
    barangay_id bigint NOT NULL
);


ALTER TABLE public.residents_household OWNER TO postgres;

--
-- TOC entry 247 (class 1259 OID 17685)
-- Name: residents_household_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.residents_household ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.residents_household_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 265 (class 1259 OID 17866)
-- Name: residents_incidentreport; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.residents_incidentreport (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    description text NOT NULL,
    report_type character varying(20) NOT NULL,
    respondent_name character varying(100),
    status character varying(20) NOT NULL,
    location_point public.geometry(Point,4326),
    location_address character varying(255),
    schedule_date date,
    schedule_time time without time zone,
    location character varying(200) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    barangay_id bigint,
    resident_id bigint
);


ALTER TABLE public.residents_incidentreport OWNER TO postgres;

--
-- TOC entry 264 (class 1259 OID 17865)
-- Name: residents_incidentreport_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.residents_incidentreport ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.residents_incidentreport_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 267 (class 1259 OID 17882)
-- Name: residents_notification; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.residents_notification (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    message text NOT NULL,
    is_read boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint
);


ALTER TABLE public.residents_notification OWNER TO postgres;

--
-- TOC entry 266 (class 1259 OID 17881)
-- Name: residents_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.residents_notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.residents_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 261 (class 1259 OID 17839)
-- Name: residents_official; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.residents_official (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    "position" character varying(50) NOT NULL,
    term_start date NOT NULL,
    term_end date NOT NULL,
    is_active boolean NOT NULL,
    barangay_id bigint
);


ALTER TABLE public.residents_official OWNER TO postgres;

--
-- TOC entry 260 (class 1259 OID 17838)
-- Name: residents_official_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.residents_official ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.residents_official_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 250 (class 1259 OID 17701)
-- Name: residents_resident; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.residents_resident (
    id bigint NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    middle_name character varying(100),
    date_of_birth date,
    gender character varying(10) NOT NULL,
    contact_number character varying(15),
    email character varying(254),
    occupation character varying(100),
    is_voter boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    household_id bigint,
    user_id bigint,
    barangay_id bigint,
    age_range character varying(20),
    birthplace character varying(255),
    citizenship character varying(100) NOT NULL,
    civil_status character varying(20) NOT NULL,
    college character varying(255),
    educational_attainment character varying(100) NOT NULL,
    elementary_school character varying(255),
    employment_history text,
    employment_status character varying(20) NOT NULL,
    high_school character varying(255),
    income numeric(10,2),
    is_student boolean NOT NULL,
    profile_status character varying(20) NOT NULL,
    religion character varying(100),
    residency_status character varying(50) NOT NULL,
    resident_code character varying(50),
    zone_street_purok character varying(255),
    father_id bigint,
    father_name character varying(255),
    has_children boolean NOT NULL,
    is_present_address_same_as_permanent boolean CONSTRAINT residents_resident_is_present_address_same_as_permanen_not_null NOT NULL,
    mother_id bigint,
    mother_name character varying(255),
    present_address character varying(255),
    residency_type character varying(20) NOT NULL,
    years_in_barangay integer NOT NULL,
    children_details text,
    permanent_address character varying(255),
    is_verified boolean NOT NULL,
    photo character varying(100),
    num_children integer NOT NULL,
    elementary_graduated_at character varying(255),
    high_school_graduated_at character varying(255),
    student_level character varying(20),
    is_father_deceased boolean NOT NULL,
    is_mother_deceased boolean NOT NULL,
    mother_maiden_name character varying(255),
    spouse_name character varying(255),
    is_active boolean NOT NULL,
    CONSTRAINT residents_resident_num_children_check CHECK ((num_children >= 0)),
    CONSTRAINT residents_resident_years_in_barangay_check CHECK ((years_in_barangay >= 0))
);


ALTER TABLE public.residents_resident OWNER TO postgres;

--
-- TOC entry 249 (class 1259 OID 17700)
-- Name: residents_resident_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.residents_resident ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.residents_resident_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 257 (class 1259 OID 17788)
-- Name: residents_residentdocument; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.residents_residentdocument (
    id bigint NOT NULL,
    document character varying(100) NOT NULL,
    description character varying(255) NOT NULL,
    uploaded_at timestamp with time zone NOT NULL,
    resident_id bigint NOT NULL
);


ALTER TABLE public.residents_residentdocument OWNER TO postgres;

--
-- TOC entry 256 (class 1259 OID 17787)
-- Name: residents_residentdocument_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.residents_residentdocument ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.residents_residentdocument_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 263 (class 1259 OID 17851)
-- Name: residents_service; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.residents_service (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    description text NOT NULL,
    requirements text NOT NULL,
    processing_time character varying(100) NOT NULL,
    is_active boolean NOT NULL,
    barangay_id bigint NOT NULL
);


ALTER TABLE public.residents_service OWNER TO postgres;

--
-- TOC entry 262 (class 1259 OID 17850)
-- Name: residents_service_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.residents_service ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.residents_service_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 271 (class 1259 OID 17983)
-- Name: residents_servicerequest; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.residents_servicerequest (
    id bigint NOT NULL,
    request_message text,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    barangay_id bigint NOT NULL,
    resident_id bigint NOT NULL,
    service_id bigint NOT NULL
);


ALTER TABLE public.residents_servicerequest OWNER TO postgres;

--
-- TOC entry 270 (class 1259 OID 17982)
-- Name: residents_servicerequest_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.residents_servicerequest ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.residents_servicerequest_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 17563)
-- Name: users_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    role character varying(20) NOT NULL,
    is_active boolean NOT NULL,
    barangay character varying(100),
    is_approved boolean NOT NULL,
    barangay_name character varying(100),
    data_privacy_consent boolean NOT NULL
);


ALTER TABLE public.users_user OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 17584)
-- Name: users_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.users_user_groups OWNER TO postgres;

--
-- TOC entry 237 (class 1259 OID 17583)
-- Name: users_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 17562)
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 17593)
-- Name: users_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.users_user_user_permissions OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 17592)
-- Name: users_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 6238 (class 0 OID 17516)
-- Dependencies: 232
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- TOC entry 6240 (class 0 OID 17526)
-- Dependencies: 234
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- TOC entry 6236 (class 0 OID 17506)
-- Dependencies: 230
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add user	6	add_user
22	Can change user	6	change_user
23	Can delete user	6	delete_user
24	Can view user	6	view_user
25	Can add household	7	add_household
26	Can change household	7	change_household
27	Can delete household	7	delete_household
28	Can view household	7	view_household
29	Can add resident	8	add_resident
30	Can change resident	8	change_resident
31	Can delete resident	8	delete_resident
32	Can view resident	8	view_resident
33	Can add disaster prone area	9	add_disasterpronearea
34	Can change disaster prone area	9	change_disasterpronearea
35	Can delete disaster prone area	9	delete_disasterpronearea
36	Can view disaster prone area	9	view_disasterpronearea
37	Can add infrastructure	10	add_infrastructure
38	Can change infrastructure	10	change_infrastructure
39	Can delete infrastructure	10	delete_infrastructure
40	Can view infrastructure	10	view_infrastructure
41	Can add barangay service	11	add_barangayservice
42	Can change barangay service	11	change_barangayservice
43	Can delete barangay service	11	delete_barangayservice
44	Can view barangay service	11	view_barangayservice
45	Can add announcement	12	add_announcement
46	Can change announcement	12	change_announcement
47	Can delete announcement	12	delete_announcement
48	Can view announcement	12	view_announcement
49	Can add resident document	13	add_residentdocument
50	Can change resident document	13	change_residentdocument
51	Can delete resident document	13	delete_residentdocument
52	Can view resident document	13	view_residentdocument
53	Can add barangay	14	add_barangay
54	Can change barangay	14	change_barangay
55	Can delete barangay	14	delete_barangay
56	Can view barangay	14	view_barangay
57	Can add incident report	15	add_incidentreport
58	Can change incident report	15	change_incidentreport
59	Can delete incident report	15	delete_incidentreport
60	Can view incident report	15	view_incidentreport
61	Can add notification	16	add_notification
62	Can change notification	16	change_notification
63	Can delete notification	16	delete_notification
64	Can view notification	16	view_notification
65	Can add official	17	add_official
66	Can change official	17	change_official
67	Can delete official	17	delete_official
68	Can view official	17	view_official
69	Can add service	18	add_service
70	Can change service	18	change_service
71	Can delete service	18	delete_service
72	Can view service	18	view_service
73	Can add evacuation site	19	add_evacuationsite
74	Can change evacuation site	19	change_evacuationsite
75	Can delete evacuation site	19	delete_evacuationsite
76	Can view evacuation site	19	view_evacuationsite
77	Can add service request	20	add_servicerequest
78	Can change service request	20	change_servicerequest
79	Can delete service request	20	delete_servicerequest
80	Can view service request	20	view_servicerequest
81	Can add issued document	21	add_issueddocument
82	Can change issued document	21	change_issueddocument
83	Can delete issued document	21	delete_issueddocument
84	Can view issued document	21	view_issueddocument
85	Can add transaction log	22	add_transactionlog
86	Can change transaction log	22	change_transactionlog
87	Can delete transaction log	22	delete_transactionlog
88	Can view transaction log	22	view_transactionlog
89	Can add receipt	23	add_receipt
90	Can change receipt	23	change_receipt
91	Can delete receipt	23	delete_receipt
92	Can view receipt	23	view_receipt
\.


--
-- TOC entry 6279 (class 0 OID 18058)
-- Dependencies: 273
-- Data for Name: barangay_services_issueddocument; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.barangay_services_issueddocument (id, document_type, document_number, purpose, issued_at, is_paid, barangay_id, issued_by_id, resident_id) FROM stdin;
\.


--
-- TOC entry 6283 (class 0 OID 18090)
-- Dependencies: 277
-- Data for Name: barangay_services_receipt; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.barangay_services_receipt (id, receipt_number, amount, tax_fee, total_amount, payment_date, issued_document_id, processed_by_id) FROM stdin;
\.


--
-- TOC entry 6281 (class 0 OID 18076)
-- Dependencies: 275
-- Data for Name: barangay_services_transactionlog; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.barangay_services_transactionlog (id, action, model_name, object_id, details, "timestamp", ip_address, user_id) FROM stdin;
1	ISSUE	IssuedDocument	1	Issued Certificate of Indigency to Rona Mira Bitancor Lucañas	2026-04-27 00:12:44.467191+08	127.0.0.1	11
\.


--
-- TOC entry 6248 (class 0 OID 17631)
-- Dependencies: 242
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-04-05 09:02:31.114168+08	5	ronamira.lucanas	2	[{"changed": {"fields": ["password"]}}]	6	1
2	2026-04-05 09:07:28.21404+08	9	Bayog, Ormoc City	3		14	1
3	2026-04-05 09:10:15.252689+08	10	Bayog, Ormoc City	2	[{"changed": {"fields": ["Captain name"]}}]	14	1
4	2026-04-05 09:10:37.807798+08	1	Sabang Bao, Ormoc City	2	[{"changed": {"fields": ["Captain name"]}}]	14	1
5	2026-04-05 09:11:17.91638+08	12	brgybayog	2	[{"changed": {"fields": ["password"]}}]	6	1
6	2026-04-22 15:32:56.617226+08	1	Sabang Bao Flood Zone - Flood Prone	2	[]	9	1
7	2026-04-22 17:31:58.930049+08	13	brgysouth	2	[{"changed": {"fields": ["password"]}}]	6	1
8	2026-04-22 17:32:37.794493+08	13	brgysouth	2	[]	6	1
9	2026-04-22 17:37:52.745638+08	13	brgysouth	2	[{"changed": {"fields": ["password"]}}]	6	1
10	2026-04-22 17:37:58.432906+08	13	brgysouth	2	[]	6	1
11	2026-04-22 17:38:12.326668+08	13	brgysouth	2	[{"changed": {"fields": ["Is active"]}}]	6	1
12	2026-04-27 13:09:46.797735+08	13	brgysouth	2	[{"changed": {"fields": ["password"]}}]	6	1
\.


--
-- TOC entry 6234 (class 0 OID 17494)
-- Dependencies: 228
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	users	user
7	residents	household
8	residents	resident
9	gis_mapping	disasterpronearea
10	gis_mapping	infrastructure
11	residents	barangayservice
12	residents	announcement
13	residents	residentdocument
14	residents	barangay
15	residents	incidentreport
16	residents	notification
17	residents	official
18	residents	service
19	gis_mapping	evacuationsite
20	residents	servicerequest
21	barangay_services	issueddocument
22	barangay_services	transactionlog
23	barangay_services	receipt
\.


--
-- TOC entry 6232 (class 0 OID 17480)
-- Dependencies: 226
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-03-30 23:03:59.151452+08
2	contenttypes	0002_remove_content_type_name	2026-03-30 23:03:59.171906+08
3	auth	0001_initial	2026-03-30 23:03:59.288812+08
4	auth	0002_alter_permission_name_max_length	2026-03-30 23:03:59.301684+08
5	auth	0003_alter_user_email_max_length	2026-03-30 23:03:59.311489+08
6	auth	0004_alter_user_username_opts	2026-03-30 23:03:59.325678+08
7	auth	0005_alter_user_last_login_null	2026-03-30 23:03:59.338504+08
8	auth	0006_require_contenttypes_0002	2026-03-30 23:03:59.343238+08
9	auth	0007_alter_validators_add_error_messages	2026-03-30 23:03:59.355853+08
10	auth	0008_alter_user_username_max_length	2026-03-30 23:03:59.36993+08
11	auth	0009_alter_user_last_name_max_length	2026-03-30 23:03:59.383998+08
12	auth	0010_alter_group_name_max_length	2026-03-30 23:03:59.401673+08
13	auth	0011_update_proxy_permissions	2026-03-30 23:03:59.412293+08
14	auth	0012_alter_user_first_name_max_length	2026-03-30 23:03:59.421902+08
15	users	0001_initial	2026-03-30 23:03:59.592951+08
16	admin	0001_initial	2026-03-30 23:03:59.66723+08
17	admin	0002_logentry_remove_auto_add	2026-03-30 23:03:59.6845+08
18	admin	0003_logentry_add_action_flag_choices	2026-03-30 23:03:59.695165+08
19	gis_mapping	0001_initial	2026-03-30 23:03:59.754305+08
20	residents	0001_initial	2026-03-30 23:03:59.815521+08
21	sessions	0001_initial	2026-03-30 23:03:59.837877+08
22	residents	0002_resident_user_barangayservice_announcement	2026-03-31 17:02:49.267321+08
23	users	0002_alter_user_role	2026-03-31 17:02:49.293855+08
24	residents	0003_alter_resident_user_residentdocument	2026-03-31 17:20:57.84758+08
25	residents	0004_alter_resident_date_of_birth_and_more	2026-03-31 17:39:53.298403+08
26	users	0002_ensure_user_columns	2026-03-31 19:11:42.042521+08
27	residents	0005_ensure_resident_barangay_column	2026-03-31 19:27:16.145931+08
28	residents	0006_ensure_core_tables	2026-03-31 21:31:24.604997+08
29	residents	0007_ensure_household_barangay_fk	2026-03-31 21:48:00.407272+08
30	residents	0008_barangay_admin_user	2026-03-31 21:59:47.767278+08
31	residents	0009_ensure_announcement_barangay_fk	2026-03-31 22:25:07.557545+08
32	residents	0010_announcement_created_by_state	2026-03-31 22:40:43.038159+08
33	residents	0011_incidentreport_add_resident_barangay	2026-03-31 22:44:09.879356+08
34	residents	0012_official_notification_fks_and_resident_user_state	2026-03-31 23:06:29.72784+08
35	gis_mapping	0002_barangay_links_and_evacuation_sites	2026-04-05 08:14:53.347642+08
36	gis_mapping	0002_disasterpronearea_barangay_ref_and_more	2026-04-05 08:14:53.35722+08
37	residents	0013_seed_selected_barangays	2026-04-05 08:38:11.164299+08
38	residents	0014_household_legacy_barangay_nullable	2026-04-05 08:57:43.707569+08
39	residents	0015_announcement_legacy_barangay_nullable	2026-04-05 09:16:25.427635+08
40	residents	0016_servicerequest	2026-04-05 09:25:37.394325+08
41	gis_mapping	0003_alter_infrastructure_barangay	2026-04-22 17:15:15.867856+08
42	residents	0017_resident_age_range_resident_birthplace_and_more	2026-04-26 19:09:29.307056+08
43	residents	0018_resident_father_resident_father_name_and_more	2026-04-26 19:37:16.377776+08
44	users	0003_user_data_privacy_consent	2026-04-26 19:37:16.408136+08
45	residents	0019_resident_children_details	2026-04-26 19:42:57.873061+08
46	residents	0020_resident_permanent_address	2026-04-26 19:48:25.891089+08
47	residents	0021_resident_is_verified_resident_photo	2026-04-26 19:52:59.569805+08
48	barangay_services	0001_initial	2026-04-26 19:52:59.763464+08
49	residents	0022_barangay_boundary	2026-04-26 20:34:22.666114+08
50	residents	0023_resident_num_children	2026-04-26 20:47:27.411357+08
51	residents	0024_resident_elementary_graduated_at_and_more	2026-04-26 21:09:44.902822+08
52	residents	0025_resident_is_father_deceased_and_more	2026-04-26 21:30:26.50859+08
53	residents	0026_resident_spouse_name_alter_resident_civil_status	2026-04-26 21:58:32.91069+08
54	residents	0027_announcement_end_date_announcement_start_date	2026-04-26 23:04:55.106717+08
55	residents	0028_barangay_is_active_resident_is_active	2026-04-26 23:48:39.218341+08
56	residents	0029_barangay_contact_number	2026-04-27 00:07:46.651251+08
57	users	0004_alter_user_role	2026-04-27 00:07:46.673903+08
\.


--
-- TOC entry 6257 (class 0 OID 17725)
-- Dependencies: 251
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
nsfblbjeisax7zuj7t9t7c163fll84fp	.eJxVjEEOwiAQRe_C2hCgtIBL956BzAyDVA0kpV0Z765NutDtf-_9l4iwrSVunZc4J3EWWpx-NwR6cN1BukO9NUmtrsuMclfkQbu8tsTPy-H-HRTo5Vsbl5OxPLiBgieXvZ6UIkDCgFrZAcAEBGc9ACgNY55cIjcazz6QSizeH-sjOFg:1w9CB4:dTe-h-IaudpQtgnSlfA42LYQh_F7F-q2mcvKlGd-lqw	2026-04-19 09:21:26.309765+08
nb0iv379f4w0svi5shcu8xrydrmcpn59	.eJxVjEEOwiAQRe_C2pAB0tBx6d4zkIEZpGogKe2q8e6GpAvd_vfeP1SgfSth77KGhdVVGVCX3zFSekkdhJ9UH02nVrd1iXoo-qRd3xvL-3a6fweFehk1JmQPZDALAkKcZ-dsjiJTchkEbQImMCaZ7C1PJB4jiTWZQYiz-nwBHp05Rw:1w9CFf:D_1421j-VHJV92GHWYy6aUUjCUcFtxxmxv23CuxhWT8	2026-04-19 09:26:11.470625+08
irxi5v9j5b3fdvuz8556606l3429oui2	.eJxVjDsOwjAQBe_iGlnrTzYxJX3OEK29CwkgW4qTCnF3sJQC2jcz76Um2rd52qus08LqrFCdfrdI6SG5Ab5TvhWdSt7WJeqm6INWPRaW5-Vw_w5mqnOrGVyEJBiSBw_YWe6gv1KHzrIVMCChD5hgQDJigxksBUb2_tsZ16v3B81vNtM:1w7ZYh:bV6XlEn7DmCpl1a0KFBxPA0BQ8Wj1XzPTkia7QqHzVs	2026-04-14 21:55:07.449526+08
hm26k4n5sko9pi4uypa4o2nutefe75jt	.eJxVjDsOwjAQBe_iGlnrTzYxJX3OEK29CwkgW4qTCnF3sJQC2jcz76Um2rd52qus08LqrFCdfrdI6SG5Ab5TvhWdSt7WJeqm6INWPRaW5-Vw_w5mqnOrGVyEJBiSBw_YWe6gv1KHzrIVMCChD5hgQDJigxksBUb2_tsZ16v3B81vNtM:1w7ZZ0:uw4sXKyn5qbs9RxVekvGdD7U1JH3kIEJyxUlui_-_a4	2026-04-14 21:55:26.775992+08
rupx1nkv3rp4sy9ycibwqvxg57zq1f22	.eJxVjEsOAiEQBe_C2hA-ARqX7j0DaT4towaSYWZlvLuSzEK3VfXeiwXctxr2UdawZHZmUrLTL4yYHqVNk-_Ybp2n3rZ1iXwm_LCDX3suz8vR_h1UHHWuDTm0hCQAdYnKZuWthC8SaBxGMMZIAVFrodAnD6ZgcgWSy6SQiL0_GdI4yw:1wH2Ru:sMdorG3EM8t1YhPzyRzWrdIHocxhr4lCEdk6UAPdkLU	2026-05-11 00:35:14.678369+08
jizib3vu9aq1bn4ep7twfhpbfnekby5g	.eJxVjMsOwiAQRf-FtSHATHi4dO83EGAGqRqalHZl_Hdt0oVu7znnvkRM29riNniJE4mz0CBOv2NO5cF9J3RP_TbLMvd1mbLcFXnQIa8z8fNyuH8HLY32rVmhDQ4Ta2uxOrQEjIUwBzBBgy_VKKcrsfVa5ZAxeAauJnvAkqoR7w_0kDfm:1wFU3W:5pVnTk7-m4PqzRUpyXgZuCQztY-SmBZVybEs56XveKI	2026-05-06 17:39:38.702583+08
tvuetn0hawh32dhj5owndcfh09q8bgmt	.eJxVjEsOAiEQBe_C2hAYms-4dO8ZSNMNMmogmc_KeHedZBa6fVX1XiLitta4LXmOE4uz0EacfseE9MhtJ3zHduuSelvnKcldkQdd5LVzfl4O9--g4lK_dfEBnA-KswabtTXgEriR3GgGSm4MBIVKKoAUCinFqKwx6AfAQppZvD_6tThp:1wIfAw:UJWa0KwgA40A5hpjDm7x75YwLwbyVeYz6yIBTF2oX4E	2026-05-15 12:08:26.488081+08
\.


--
-- TOC entry 6250 (class 0 OID 17658)
-- Dependencies: 244
-- Data for Name: gis_mapping_disasterpronearea; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.gis_mapping_disasterpronearea (id, name, type, boundary, risk_level, barangay_ref_id) FROM stdin;
7	Bayog Flood Zone	FLOOD	0103000020E610000001000000060000003E5C72DC29225F405A4B0169FF2B264034D769A4A5225F408CD99255112E2640350BB43BA4225F40861E317A6E312640B1FCF9B660225F4074D3669C863026402CBAF59A1E225F40D8BB3FDEAB2E26403E5C72DC29225F405A4B0169FF2B2640	2	10
1	Sabang Bao Flood Zone	FLOOD	0103000020E6100000010000000500000067D13B1570225F406AA510C82526264092E68F696D225F40BA6587F887252640DC9F8B868C225F4049BE124889252640E6CB0BB08F225F403126FDBD1426264067D13B1570225F406AA510C825262640	2	1
\.


--
-- TOC entry 6275 (class 0 OID 17961)
-- Dependencies: 269
-- Data for Name: gis_mapping_evacuationsite; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.gis_mapping_evacuationsite (id, name, location, capacity, barangay_id) FROM stdin;
4	Bayog Evacuation Center	0101000020E6100000F6285C8FC2255F407B14AE47E1FA2540	250	10
5	Sabang Bao Elementary School	0101000020E610000002D53F8864225F40F8FC304278242640	500	1
6	Barangay Court	0101000020E6100000D4B837BF61225F403830B95164252640	100	1
\.


--
-- TOC entry 6252 (class 0 OID 17671)
-- Dependencies: 246
-- Data for Name: gis_mapping_infrastructure; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.gis_mapping_infrastructure (id, name, type, location, barangay, barangay_ref_id) FROM stdin;
1	Barangay Hall	BARANGAY_HALL	0101000020E61000004512BD8C62225F402CB6494563252640	Sabang Bao	1
2	Sabang Bao Elementary School	SCHOOL	0101000020E6100000FFB3E6C75F225F40EF8CB62A89242640	Sabang Bao	1
3	Rustico Capahi Sr. Memorial National High School	SCHOOL	0101000020E6100000607825C973225F4097749483D9242640	Sabang Bao	1
4	Port of Ormoc	OTHER	0101000020E6100000790778D2C2265F404DD9E90775012640	Brgy. South	11
\.


--
-- TOC entry 6261 (class 0 OID 17762)
-- Dependencies: 255
-- Data for Name: residents_announcement; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.residents_announcement (id, title, content, barangay, is_global, created_at, created_by_id, barangay_id, end_date, start_date) FROM stdin;
\.


--
-- TOC entry 6265 (class 0 OID 17812)
-- Dependencies: 259
-- Data for Name: residents_barangay; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.residents_barangay (id, name, municipality, email, captain_name, is_approved, created_at, admin_user_id, boundary, is_active, contact_number) FROM stdin;
10	Bayog	Ormoc City	bayog@bmis.local	Bayog Captain	t	2026-05-01 11:31:09.444591+08	12	\N	t	\N
1	Sabang Bao	Ormoc City	auto_sabangbao@example.com	Sabang Bao Captain	t	2026-05-01 11:31:09.458172+08	11	0103000020E61000000100000005000000ECBDF8A23D225F4039F2406491262640F6EE8FF7AA225F40D26D895C7026264027158DB5BF225F40C217265305232640A5BDC11726225F406F9F55664A232640ECBDF8A23D225F4039F2406491262640	t	\N
11	Brgy. South	Ormoc City	brgysouth@gmail.com	Someone	t	2026-05-01 11:31:09.462724+08	13	0103000020E6100000010000000A000000F790F0BDBF265F40892991442F0326407C0E2C47C8265F40D41055F8330426409D9B36E334275F40F54883DBDA022640081EDFDE35275F40FF5C34643C022640D82B2CB81F275F40DA53724EEC012640A6B73F170D275F409C69C2F6930126400BB5A679C7265F4086CB2A6C06002640DA740470B3265F40DA53724EEC0126402C64AE0CAA265F40D714C8EC2C022640F790F0BDBF265F40892991442F032640	t	\N
\.


--
-- TOC entry 6259 (class 0 OID 17746)
-- Dependencies: 253
-- Data for Name: residents_barangayservice; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.residents_barangayservice (id, service_type, description, status, barangay, requested_at, updated_at, resident_id) FROM stdin;
\.


--
-- TOC entry 6254 (class 0 OID 17686)
-- Dependencies: 248
-- Data for Name: residents_household; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.residents_household (id, household_number, address, location, barangay, created_at, barangay_id) FROM stdin;
17	TEMP - 23456	Brgy. Bayog, Ormoc City	0101000020E6100000680586AC6E225F4080D8D2A3A92E2640	\N	2026-04-22 16:10:39.407284+08	10
12	TEMP-358423B8	Purok Santol, Sabang Bao, Ormoc City	0101000020E6100000F94D61A582225F409CFD8172DB262640	\N	2026-03-31 17:57:19.926698+08	1
18	Temp - 0987	Brgy. Bayog, Ormoc City	0101000020E6100000200890A163225F40AF3F89CF9D282640	\N	2026-04-22 16:24:55.874301+08	1
16	House 01	Purok Santol, Sabang Bao	0101000020E6100000AFB0E07EC0225F405F5D15A8C5282640	\N	2026-04-05 09:00:07.416002+08	1
19	HH-SOUTH-001	Aviles St. Brgy. South	0101000020E6100000137F1475E6265F40ECA353573E032640	\N	2026-04-26 23:13:13.109347+08	11
\.


--
-- TOC entry 6271 (class 0 OID 17866)
-- Dependencies: 265
-- Data for Name: residents_incidentreport; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.residents_incidentreport (id, title, description, report_type, respondent_name, status, location_point, location_address, schedule_date, schedule_time, location, created_at, updated_at, barangay_id, resident_id) FROM stdin;
\.


--
-- TOC entry 6273 (class 0 OID 17882)
-- Dependencies: 267
-- Data for Name: residents_notification; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.residents_notification (id, title, message, is_read, created_at, user_id) FROM stdin;
1	Report Update: Thief	Your report status is now 'In Review'. 	t	2026-04-05 09:16:53.747587+08	5
2	Profile Approved	Your resident profile has been verified and approved by your barangay officials.	t	2026-04-27 13:03:15.974454+08	5
13	Profile Approved	Your resident profile has been verified and approved by your barangay officials.	f	2026-05-01 12:09:39.376325+08	10
14	Profile Approved	Your resident profile has been verified and approved by your barangay officials.	f	2026-05-01 12:09:42.922729+08	10
\.


--
-- TOC entry 6267 (class 0 OID 17839)
-- Dependencies: 261
-- Data for Name: residents_official; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.residents_official (id, name, "position", term_start, term_end, is_active, barangay_id) FROM stdin;
1	Juan ABCDE Dela Cruz	CAPTAIN	2026-05-01	2026-05-02	t	11
\.


--
-- TOC entry 6256 (class 0 OID 17701)
-- Dependencies: 250
-- Data for Name: residents_resident; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.residents_resident (id, first_name, last_name, middle_name, date_of_birth, gender, contact_number, email, occupation, is_voter, created_at, updated_at, household_id, user_id, barangay_id, age_range, birthplace, citizenship, civil_status, college, educational_attainment, elementary_school, employment_history, employment_status, high_school, income, is_student, profile_status, religion, residency_status, resident_code, zone_street_purok, father_id, father_name, has_children, is_present_address_same_as_permanent, mother_id, mother_name, present_address, residency_type, years_in_barangay, children_details, permanent_address, is_verified, photo, num_children, elementary_graduated_at, high_school_graduated_at, student_level, is_father_deceased, is_mother_deceased, mother_maiden_name, spouse_name, is_active) FROM stdin;
44	Rona Mira	Lucañas	Bitancor	1997-08-17	FEMALE	09489090550	ronamira.alr@gmail.com	Teacher	t	2026-05-01 11:31:46.872132+08	2026-05-01 11:31:46.872132+08	12	5	1	YOUNG_ADULTHOOD	Pasig City	Filipino	SINGLE	\N	COLLEGE_GRAD	\N		EMPLOYED	\N	10000.00	f	APPROVED	Seventh Day Adventist	PERMANENT	RES-FDE2EC4D	Purok Santol	\N	Ronnie Lucañas	f	t	\N	\N	Purok Santol, Sabang Bao	HOUSE_OWNER	28		Purok Santol, Sabang Bao	t	resident_photos/1.png	0	\N	\N	\N	t	f	Mayra Bitancor	\N	t
48	Juan	Dela Cruz	ABCDE	2000-01-01	MALE	09215468854	juandelacruz@gmail.com	Teacher	t	2026-05-01 11:31:46.840759+08	2026-05-01 12:09:42.912867+08	19	10	11	YOUNG_ADULTHOOD	Pasig City	Filipino	SINGLE	\N	COLLEGE_GRAD	\N	None	EMPLOYED	\N	20000.00	f	APPROVED	Seventh Day Adventist	PERMANENT	RES-67937153	Aviles St.	\N	ABC	f	t	\N	\N	Aviles St. Brgy. South	HOUSE_OWNER	7		Aviles St. Brgy. South	f	resident_photos/452317109_122096719574435695_4091806308542152255_n.jpg	0	\N	\N	\N	f	f	DEF	\N	t
\.


--
-- TOC entry 6263 (class 0 OID 17788)
-- Dependencies: 257
-- Data for Name: residents_residentdocument; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.residents_residentdocument (id, document, description, uploaded_at, resident_id) FROM stdin;
\.


--
-- TOC entry 6269 (class 0 OID 17851)
-- Dependencies: 263
-- Data for Name: residents_service; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.residents_service (id, name, description, requirements, processing_time, is_active, barangay_id) FROM stdin;
1	Cedula	Cedula	Valid ID	5 minutes	t	1
2	Brgy. Certificate	Brgy. Certificate	Valid Id, and 10 pesos	10 minutes	t	1
3	Barangay Clearance	Clearance	ID	1 day	t	1
\.


--
-- TOC entry 6277 (class 0 OID 17983)
-- Dependencies: 271
-- Data for Name: residents_servicerequest; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.residents_servicerequest (id, request_message, status, created_at, updated_at, barangay_id, resident_id, service_id) FROM stdin;
\.


--
-- TOC entry 5897 (class 0 OID 16708)
-- Dependencies: 221
-- Data for Name: spatial_ref_sys; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.spatial_ref_sys (srid, auth_name, auth_srid, srtext, proj4text) FROM stdin;
\.


--
-- TOC entry 6242 (class 0 OID 17563)
-- Dependencies: 236
-- Data for Name: users_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, date_joined, role, is_active, barangay, is_approved, barangay_name, data_privacy_consent) FROM stdin;
12	pbkdf2_sha256$600000$4985E1S6lckXj9FlIfJT5j$5+vvd9a+y0UYmJxPeYT8EZW7pkTr4/1qKLilfnVLedo=	2026-04-22 16:56:04.254281+08	f	brgybayog			bayog@bmis.local	f	2026-04-05 09:08:58.333631+08	BARANGAY	t	\N	t	Bayog	f
1	pbkdf2_sha256$600000$xZhvrhOlxvpE9E8ty6yHmQ$WNIewBb5/FfQ8AfluU1nsDrwyeNw5ift7r7omulKptI=	2026-05-01 11:39:53.784761+08	t	admin			admin@example.com	t	2026-03-30 23:05:00.050666+08	ADMIN	t	\N	t	\N	f
8	pbkdf2_sha256$600000$71cvlQUXXqqA9GdHDEOoT7$/Mq4LkniSvHSPjtPIMV57u+J0FPNUp4hQSuZHkwrhmo=	2026-04-05 08:47:34.998891+08	f	sysadmin			sysadmin@example.com	f	2026-03-31 22:34:15.32695+08	ADMIN	t	\N	t	\N	f
11	pbkdf2_sha256$600000$KWIFHqwwVQxVHZ3XCIZTrb$uCgiE/bfL888TDVUHA/J2fNQqv3/50am7DQpoa9XHB0=	2026-05-01 11:47:45.739264+08	f	brgysabangbao			sabangbao@gmail.com	f	2026-03-31 23:27:22.591576+08	BARANGAY	t	\N	t	Sabang Bao	f
5	pbkdf2_sha256$600000$8A7JPV9ec5XxhFfGEqU1hj$smgmDQBsZ1lkiGofEqqnAj6mmrO1L3VHw+a2Ri47BMc=	2026-05-01 12:07:13.304273+08	f	ronamira.lucanas			ronamira.alr@gmail.com	f	2026-03-31 17:39:08.092421+08	RESIDENT	t	\N	t	Sabang Bao	f
13	pbkdf2_sha256$600000$QkViUGvHV1HOIjRBSAO1p6$eExWD+8UcJFuYgA/Onrw3cfxWou553fUdPyGBJ3CpJE=	2026-05-01 12:08:26.478156+08	f	brgysouth			brgysouth@gmail.com	f	2026-04-22 17:30:45+08	BARANGAY	t	\N	t	Brgy. South	f
10	pbkdf2_sha256$600000$xNX1QAjik3uyjnSqIEt5wO$02VWmDrQquWofQhYAluguH8wbv2S92iY3WRyz7o6HCA=	2026-04-27 13:04:15.943583+08	f	resident1			resident1@example.com	f	2026-03-31 23:17:26.646353+08	RESIDENT	t	\N	t	Brgy. South	f
\.


--
-- TOC entry 6244 (class 0 OID 17584)
-- Dependencies: 238
-- Data for Name: users_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- TOC entry 6246 (class 0 OID 17593)
-- Dependencies: 240
-- Data for Name: users_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- TOC entry 6290 (class 0 OID 0)
-- Dependencies: 231
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- TOC entry 6291 (class 0 OID 0)
-- Dependencies: 233
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- TOC entry 6292 (class 0 OID 0)
-- Dependencies: 229
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 92, true);


--
-- TOC entry 6293 (class 0 OID 0)
-- Dependencies: 272
-- Name: barangay_services_issueddocument_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.barangay_services_issueddocument_id_seq', 1, true);


--
-- TOC entry 6294 (class 0 OID 0)
-- Dependencies: 276
-- Name: barangay_services_receipt_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.barangay_services_receipt_id_seq', 1, false);


--
-- TOC entry 6295 (class 0 OID 0)
-- Dependencies: 274
-- Name: barangay_services_transactionlog_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.barangay_services_transactionlog_id_seq', 1, true);


--
-- TOC entry 6296 (class 0 OID 0)
-- Dependencies: 241
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 12, true);


--
-- TOC entry 6297 (class 0 OID 0)
-- Dependencies: 227
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 23, true);


--
-- TOC entry 6298 (class 0 OID 0)
-- Dependencies: 225
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 57, true);


--
-- TOC entry 6299 (class 0 OID 0)
-- Dependencies: 243
-- Name: gis_mapping_disasterpronearea_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.gis_mapping_disasterpronearea_id_seq', 8, true);


--
-- TOC entry 6300 (class 0 OID 0)
-- Dependencies: 268
-- Name: gis_mapping_evacuationsite_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.gis_mapping_evacuationsite_id_seq', 6, true);


--
-- TOC entry 6301 (class 0 OID 0)
-- Dependencies: 245
-- Name: gis_mapping_infrastructure_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.gis_mapping_infrastructure_id_seq', 4, true);


--
-- TOC entry 6302 (class 0 OID 0)
-- Dependencies: 254
-- Name: residents_announcement_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.residents_announcement_id_seq', 2, true);


--
-- TOC entry 6303 (class 0 OID 0)
-- Dependencies: 258
-- Name: residents_barangay_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.residents_barangay_id_seq', 11, true);


--
-- TOC entry 6304 (class 0 OID 0)
-- Dependencies: 252
-- Name: residents_barangayservice_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.residents_barangayservice_id_seq', 1, false);


--
-- TOC entry 6305 (class 0 OID 0)
-- Dependencies: 247
-- Name: residents_household_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.residents_household_id_seq', 19, true);


--
-- TOC entry 6306 (class 0 OID 0)
-- Dependencies: 264
-- Name: residents_incidentreport_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.residents_incidentreport_id_seq', 2, true);


--
-- TOC entry 6307 (class 0 OID 0)
-- Dependencies: 266
-- Name: residents_notification_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.residents_notification_id_seq', 14, true);


--
-- TOC entry 6308 (class 0 OID 0)
-- Dependencies: 260
-- Name: residents_official_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.residents_official_id_seq', 1, true);


--
-- TOC entry 6309 (class 0 OID 0)
-- Dependencies: 249
-- Name: residents_resident_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.residents_resident_id_seq', 49, true);


--
-- TOC entry 6310 (class 0 OID 0)
-- Dependencies: 256
-- Name: residents_residentdocument_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.residents_residentdocument_id_seq', 1, false);


--
-- TOC entry 6311 (class 0 OID 0)
-- Dependencies: 262
-- Name: residents_service_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.residents_service_id_seq', 3, true);


--
-- TOC entry 6312 (class 0 OID 0)
-- Dependencies: 270
-- Name: residents_servicerequest_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.residents_servicerequest_id_seq', 1, false);


--
-- TOC entry 6313 (class 0 OID 0)
-- Dependencies: 237
-- Name: users_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_user_groups_id_seq', 1, false);


--
-- TOC entry 6314 (class 0 OID 0)
-- Dependencies: 235
-- Name: users_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_user_id_seq', 13, true);


--
-- TOC entry 6315 (class 0 OID 0)
-- Dependencies: 239
-- Name: users_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_user_user_permissions_id_seq', 1, false);


--
-- TOC entry 5919 (class 2606 OID 17559)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 5924 (class 2606 OID 17544)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 5927 (class 2606 OID 17533)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 5921 (class 2606 OID 17522)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 5914 (class 2606 OID 17535)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 5916 (class 2606 OID 17514)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 6026 (class 2606 OID 18074)
-- Name: barangay_services_issueddocument barangay_services_issueddocument_document_number_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.barangay_services_issueddocument
    ADD CONSTRAINT barangay_services_issueddocument_document_number_key UNIQUE (document_number);


--
-- TOC entry 6029 (class 2606 OID 18072)
-- Name: barangay_services_issueddocument barangay_services_issueddocument_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.barangay_services_issueddocument
    ADD CONSTRAINT barangay_services_issueddocument_pkey PRIMARY KEY (id);


--
-- TOC entry 6035 (class 2606 OID 18105)
-- Name: barangay_services_receipt barangay_services_receipt_issued_document_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.barangay_services_receipt
    ADD CONSTRAINT barangay_services_receipt_issued_document_id_key UNIQUE (issued_document_id);


--
-- TOC entry 6037 (class 2606 OID 18101)
-- Name: barangay_services_receipt barangay_services_receipt_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.barangay_services_receipt
    ADD CONSTRAINT barangay_services_receipt_pkey PRIMARY KEY (id);


--
-- TOC entry 6041 (class 2606 OID 18103)
-- Name: barangay_services_receipt barangay_services_receipt_receipt_number_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.barangay_services_receipt
    ADD CONSTRAINT barangay_services_receipt_receipt_number_key UNIQUE (receipt_number);


--
-- TOC entry 6032 (class 2606 OID 18088)
-- Name: barangay_services_transactionlog barangay_services_transactionlog_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.barangay_services_transactionlog
    ADD CONSTRAINT barangay_services_transactionlog_pkey PRIMARY KEY (id);


--
-- TOC entry 5947 (class 2606 OID 17644)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 5909 (class 2606 OID 17504)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 5911 (class 2606 OID 17502)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 5907 (class 2606 OID 17492)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 5977 (class 2606 OID 17734)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 5952 (class 2606 OID 17669)
-- Name: gis_mapping_disasterpronearea gis_mapping_disasterpronearea_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gis_mapping_disasterpronearea
    ADD CONSTRAINT gis_mapping_disasterpronearea_pkey PRIMARY KEY (id);


--
-- TOC entry 6017 (class 2606 OID 17972)
-- Name: gis_mapping_evacuationsite gis_mapping_evacuationsite_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gis_mapping_evacuationsite
    ADD CONSTRAINT gis_mapping_evacuationsite_pkey PRIMARY KEY (id);


--
-- TOC entry 5956 (class 2606 OID 17682)
-- Name: gis_mapping_infrastructure gis_mapping_infrastructure_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gis_mapping_infrastructure
    ADD CONSTRAINT gis_mapping_infrastructure_pkey PRIMARY KEY (id);


--
-- TOC entry 5985 (class 2606 OID 17774)
-- Name: residents_announcement residents_announcement_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.residents_announcement
    ADD CONSTRAINT residents_announcement_pkey PRIMARY KEY (id);


--
-- TOC entry 5990 (class 2606 OID 17914)
-- Name: residents_barangay residents_barangay_admin_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.residents_barangay
    ADD CONSTRAINT residents_barangay_admin_user_id_key UNIQUE (admin_user_id);


--
-- TOC entry 5994 (class 2606 OID 17829)
-- Name: residents_barangay residents_barangay_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.residents_barangay
    ADD CONSTRAINT residents_barangay_email_key UNIQUE (email);


--
-- TOC entry 5997 (class 2606 OID 17827)
-- Name: residents_barangay residents_barangay_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.residents_barangay
    ADD CONSTRAINT residents_barangay_name_key UNIQUE (name);


--
-- TOC entry 5999 (class 2606 OID 17825)
-- Name: residents_barangay residents_barangay_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.residents_barangay
    ADD CONSTRAINT residents_barangay_pkey PRIMARY KEY (id);


--
-- TOC entry 5980 (class 2606 OID 17760)
-- Name: residents_barangayservice residents_barangayservice_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.residents_barangayservice
    ADD CONSTRAINT residents_barangayservice_pkey PRIMARY KEY (id);


--
-- TOC entry 5960 (class 2606 OID 17699)
-- Name: residents_household residents_household_household_number_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.residents_household
    ADD CONSTRAINT residents_household_household_number_key UNIQUE (household_number);


--
-- TOC entry 5963 (class 2606 OID 17697)
-- Name: residents_household residents_household_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.residents_household
    ADD CONSTRAINT residents_household_pkey PRIMARY KEY (id);


--
-- TOC entry 6009 (class 2606 OID 17880)
-- Name: residents_incidentreport residents_incidentreport_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.residents_incidentreport
    ADD CONSTRAINT residents_incidentreport_pkey PRIMARY KEY (id);


--
-- TOC entry 6012 (class 2606 OID 17893)
-- Name: residents_notification residents_notification_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.residents_notification
    ADD CONSTRAINT residents_notification_pkey PRIMARY KEY (id);


--
-- TOC entry 6002 (class 2606 OID 17849)
-- Name: residents_official residents_official_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.residents_official
    ADD CONSTRAINT residents_official_pkey PRIMARY KEY (id);


--
-- TOC entry 5969 (class 2606 OID 17716)
-- Name: residents_resident residents_resident_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.residents_resident
    ADD CONSTRAINT residents_resident_pkey PRIMARY KEY (id);


--
-- TOC entry 5972 (class 2606 OID 18030)
-- Name: residents_resident residents_resident_resident_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.residents_resident
    ADD CONSTRAINT residents_resident_resident_code_key UNIQUE (resident_code);


--
-- TOC entry 5974 (class 2606 OID 17739)
-- Name: residents_resident residents_resident_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.residents_resident
    ADD CONSTRAINT residents_resident_user_id_key UNIQUE (user_id);


--
-- TOC entry 5987 (class 2606 OID 17797)
-- Name: residents_residentdocument residents_residentdocument_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.residents_residentdocument
    ADD CONSTRAINT residents_residentdocument_pkey PRIMARY KEY (id);


--
-- TOC entry 6005 (class 2606 OID 17864)
-- Name: residents_service residents_service_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.residents_service
    ADD CONSTRAINT residents_service_pkey PRIMARY KEY (id);


--
-- TOC entry 6020 (class 2606 OID 17996)
-- Name: residents_servicerequest residents_servicerequest_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.residents_servicerequest
    ADD CONSTRAINT residents_servicerequest_pkey PRIMARY KEY (id);


--
-- TOC entry 5935 (class 2606 OID 17591)
-- Name: users_user_groups users_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 5938 (class 2606 OID 17603)
-- Name: users_user_groups users_user_groups_user_id_group_id_b88eab82_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_group_id_b88eab82_uniq UNIQUE (user_id, group_id);


--
-- TOC entry 5929 (class 2606 OID 17580)
-- Name: users_user users_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_pkey PRIMARY KEY (id);


--
-- TOC entry 5941 (class 2606 OID 17600)
-- Name: users_user_user_permissions users_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 5944 (class 2606 OID 17617)
-- Name: users_user_user_permissions users_user_user_permissions_user_id_permission_id_43338c45_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_permission_id_43338c45_uniq UNIQUE (user_id, permission_id);


--
-- TOC entry 5932 (class 2606 OID 17582)
-- Name: users_user users_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user
    ADD CONSTRAINT users_user_username_key UNIQUE (username);


--
-- TOC entry 5917 (class 1259 OID 17560)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 5922 (class 1259 OID 17555)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 5925 (class 1259 OID 17556)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 5912 (class 1259 OID 17541)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- TOC entry 6023 (class 1259 OID 18122)
-- Name: barangay_services_issueddocument_barangay_id_787b2f27; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX barangay_services_issueddocument_barangay_id_787b2f27 ON public.barangay_services_issueddocument USING btree (barangay_id);


--
-- TOC entry 6024 (class 1259 OID 18121)
-- Name: barangay_services_issueddocument_document_number_c1e18bfa_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX barangay_services_issueddocument_document_number_c1e18bfa_like ON public.barangay_services_issueddocument USING btree (document_number varchar_pattern_ops);


--
-- TOC entry 6027 (class 1259 OID 18123)
-- Name: barangay_services_issueddocument_issued_by_id_d9620698; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX barangay_services_issueddocument_issued_by_id_d9620698 ON public.barangay_services_issueddocument USING btree (issued_by_id);


--
-- TOC entry 6030 (class 1259 OID 18124)
-- Name: barangay_services_issueddocument_resident_id_0e3a5d34; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX barangay_services_issueddocument_resident_id_0e3a5d34 ON public.barangay_services_issueddocument USING btree (resident_id);


--
-- TOC entry 6038 (class 1259 OID 18142)
-- Name: barangay_services_receipt_processed_by_id_28dd2d2e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX barangay_services_receipt_processed_by_id_28dd2d2e ON public.barangay_services_receipt USING btree (processed_by_id);


--
-- TOC entry 6039 (class 1259 OID 18141)
-- Name: barangay_services_receipt_receipt_number_8061deb2_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX barangay_services_receipt_receipt_number_8061deb2_like ON public.barangay_services_receipt USING btree (receipt_number varchar_pattern_ops);


--
-- TOC entry 6033 (class 1259 OID 18130)
-- Name: barangay_services_transactionlog_user_id_e5b3c450; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX barangay_services_transactionlog_user_id_e5b3c450 ON public.barangay_services_transactionlog USING btree (user_id);


--
-- TOC entry 5945 (class 1259 OID 17655)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- TOC entry 5948 (class 1259 OID 17656)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- TOC entry 5975 (class 1259 OID 17736)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- TOC entry 5978 (class 1259 OID 17735)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 5949 (class 1259 OID 17974)
-- Name: gis_mapping_disasterpronearea_barangay_ref_id_640f4d9d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX gis_mapping_disasterpronearea_barangay_ref_id_640f4d9d ON public.gis_mapping_disasterpronearea USING btree (barangay_ref_id);


--
-- TOC entry 5950 (class 1259 OID 17683)
-- Name: gis_mapping_disasterpronearea_boundary_9cda7096_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX gis_mapping_disasterpronearea_boundary_9cda7096_id ON public.gis_mapping_disasterpronearea USING gist (boundary);


--
-- TOC entry 6014 (class 1259 OID 17981)
-- Name: gis_mapping_evacuationsite_barangay_id_80a79c0e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX gis_mapping_evacuationsite_barangay_id_80a79c0e ON public.gis_mapping_evacuationsite USING btree (barangay_id);


--
-- TOC entry 6015 (class 1259 OID 17980)
-- Name: gis_mapping_evacuationsite_location_302c8748_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX gis_mapping_evacuationsite_location_302c8748_id ON public.gis_mapping_evacuationsite USING gist (location);


--
-- TOC entry 5953 (class 1259 OID 17973)
-- Name: gis_mapping_infrastructure_barangay_ref_id_cbc084cc; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX gis_mapping_infrastructure_barangay_ref_id_cbc084cc ON public.gis_mapping_infrastructure USING btree (barangay_ref_id);


--
-- TOC entry 5954 (class 1259 OID 17684)
-- Name: gis_mapping_infrastructure_location_377437a0_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX gis_mapping_infrastructure_location_377437a0_id ON public.gis_mapping_infrastructure USING gist (location);


--
-- TOC entry 5982 (class 1259 OID 17925)
-- Name: residents_announcement_barangay_id_5e44ef0b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX residents_announcement_barangay_id_5e44ef0b ON public.residents_announcement USING btree (barangay_id);


--
-- TOC entry 5983 (class 1259 OID 17786)
-- Name: residents_announcement_created_by_id_67fd57a8; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX residents_announcement_created_by_id_67fd57a8 ON public.residents_announcement USING btree (created_by_id);


--
-- TOC entry 5991 (class 1259 OID 18143)
-- Name: residents_barangay_boundary_6048cb52_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX residents_barangay_boundary_6048cb52_id ON public.residents_barangay USING gist (boundary);


--
-- TOC entry 5992 (class 1259 OID 17836)
-- Name: residents_barangay_email_f443951c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX residents_barangay_email_f443951c_like ON public.residents_barangay USING btree (email varchar_pattern_ops);


--
-- TOC entry 5995 (class 1259 OID 17835)
-- Name: residents_barangay_name_71a34954_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX residents_barangay_name_71a34954_like ON public.residents_barangay USING btree (name varchar_pattern_ops);


--
-- TOC entry 5981 (class 1259 OID 17780)
-- Name: residents_barangayservice_resident_id_676a549f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX residents_barangayservice_resident_id_676a549f ON public.residents_barangayservice USING btree (resident_id);


--
-- TOC entry 5957 (class 1259 OID 17912)
-- Name: residents_household_barangay_id_62e2893c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX residents_household_barangay_id_62e2893c ON public.residents_household USING btree (barangay_id);


--
-- TOC entry 5958 (class 1259 OID 17717)
-- Name: residents_household_household_number_2900a161_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX residents_household_household_number_2900a161_like ON public.residents_household USING btree (household_number varchar_pattern_ops);


--
-- TOC entry 5961 (class 1259 OID 17718)
-- Name: residents_household_location_47c95edf_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX residents_household_location_47c95edf_id ON public.residents_household USING gist (location);


--
-- TOC entry 6006 (class 1259 OID 17936)
-- Name: residents_incidentreport_barangay_id_5e7fcc56; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX residents_incidentreport_barangay_id_5e7fcc56 ON public.residents_incidentreport USING btree (barangay_id);


--
-- TOC entry 6007 (class 1259 OID 17900)
-- Name: residents_incidentreport_location_point_c53fad90_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX residents_incidentreport_location_point_c53fad90_id ON public.residents_incidentreport USING gist (location_point);


--
-- TOC entry 6010 (class 1259 OID 17937)
-- Name: residents_incidentreport_resident_id_28d08bfe; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX residents_incidentreport_resident_id_28d08bfe ON public.residents_incidentreport USING btree (resident_id);


--
-- TOC entry 6013 (class 1259 OID 17949)
-- Name: residents_notification_user_id_7ca23f13; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX residents_notification_user_id_7ca23f13 ON public.residents_notification USING btree (user_id);


--
-- TOC entry 6000 (class 1259 OID 17948)
-- Name: residents_official_barangay_id_6e4ca7b5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX residents_official_barangay_id_6e4ca7b5 ON public.residents_official USING btree (barangay_id);


--
-- TOC entry 5964 (class 1259 OID 17837)
-- Name: residents_resident_barangay_id_105459be; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX residents_resident_barangay_id_105459be ON public.residents_resident USING btree (barangay_id);


--
-- TOC entry 5965 (class 1259 OID 18051)
-- Name: residents_resident_father_id_0c75768e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX residents_resident_father_id_0c75768e ON public.residents_resident USING btree (father_id);


--
-- TOC entry 5966 (class 1259 OID 17724)
-- Name: residents_resident_household_id_3fa81f6b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX residents_resident_household_id_3fa81f6b ON public.residents_resident USING btree (household_id);


--
-- TOC entry 5967 (class 1259 OID 18052)
-- Name: residents_resident_mother_id_c566864b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX residents_resident_mother_id_c566864b ON public.residents_resident USING btree (mother_id);


--
-- TOC entry 5970 (class 1259 OID 18031)
-- Name: residents_resident_resident_code_a067d873_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX residents_resident_resident_code_a067d873_like ON public.residents_resident USING btree (resident_code varchar_pattern_ops);


--
-- TOC entry 5988 (class 1259 OID 17803)
-- Name: residents_residentdocument_resident_id_bab15a4d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX residents_residentdocument_resident_id_bab15a4d ON public.residents_residentdocument USING btree (resident_id);


--
-- TOC entry 6003 (class 1259 OID 17899)
-- Name: residents_service_barangay_id_81006aa7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX residents_service_barangay_id_81006aa7 ON public.residents_service USING btree (barangay_id);


--
-- TOC entry 6018 (class 1259 OID 18012)
-- Name: residents_servicerequest_barangay_id_3f1326ff; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX residents_servicerequest_barangay_id_3f1326ff ON public.residents_servicerequest USING btree (barangay_id);


--
-- TOC entry 6021 (class 1259 OID 18013)
-- Name: residents_servicerequest_resident_id_fbfa067a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX residents_servicerequest_resident_id_fbfa067a ON public.residents_servicerequest USING btree (resident_id);


--
-- TOC entry 6022 (class 1259 OID 18014)
-- Name: residents_servicerequest_service_id_ee36fef6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX residents_servicerequest_service_id_ee36fef6 ON public.residents_servicerequest USING btree (service_id);


--
-- TOC entry 5933 (class 1259 OID 17615)
-- Name: users_user_groups_group_id_9afc8d0e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_groups_group_id_9afc8d0e ON public.users_user_groups USING btree (group_id);


--
-- TOC entry 5936 (class 1259 OID 17614)
-- Name: users_user_groups_user_id_5f6f5a90; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_groups_user_id_5f6f5a90 ON public.users_user_groups USING btree (user_id);


--
-- TOC entry 5939 (class 1259 OID 17629)
-- Name: users_user_user_permissions_permission_id_0b93982e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_user_permissions_permission_id_0b93982e ON public.users_user_user_permissions USING btree (permission_id);


--
-- TOC entry 5942 (class 1259 OID 17628)
-- Name: users_user_user_permissions_user_id_20aca447; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_user_permissions_user_id_20aca447 ON public.users_user_user_permissions USING btree (user_id);


--
-- TOC entry 5930 (class 1259 OID 17601)
-- Name: users_user_username_06e46fe6_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX users_user_username_06e46fe6_like ON public.users_user USING btree (username varchar_pattern_ops);


--
-- TOC entry 6043 (class 2606 OID 17550)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6044 (class 2606 OID 17545)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6042 (class 2606 OID 17536)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6073 (class 2606 OID 18106)
-- Name: barangay_services_issueddocument barangay_services_is_barangay_id_787b2f27_fk_residents; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.barangay_services_issueddocument
    ADD CONSTRAINT barangay_services_is_barangay_id_787b2f27_fk_residents FOREIGN KEY (barangay_id) REFERENCES public.residents_barangay(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6074 (class 2606 OID 18111)
-- Name: barangay_services_issueddocument barangay_services_is_issued_by_id_d9620698_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.barangay_services_issueddocument
    ADD CONSTRAINT barangay_services_is_issued_by_id_d9620698_fk_users_use FOREIGN KEY (issued_by_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6075 (class 2606 OID 18116)
-- Name: barangay_services_issueddocument barangay_services_is_resident_id_0e3a5d34_fk_residents; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.barangay_services_issueddocument
    ADD CONSTRAINT barangay_services_is_resident_id_0e3a5d34_fk_residents FOREIGN KEY (resident_id) REFERENCES public.residents_resident(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6077 (class 2606 OID 18131)
-- Name: barangay_services_receipt barangay_services_re_issued_document_id_bad8ae8e_fk_barangay_; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.barangay_services_receipt
    ADD CONSTRAINT barangay_services_re_issued_document_id_bad8ae8e_fk_barangay_ FOREIGN KEY (issued_document_id) REFERENCES public.barangay_services_issueddocument(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6078 (class 2606 OID 18136)
-- Name: barangay_services_receipt barangay_services_re_processed_by_id_28dd2d2e_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.barangay_services_receipt
    ADD CONSTRAINT barangay_services_re_processed_by_id_28dd2d2e_fk_users_use FOREIGN KEY (processed_by_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6076 (class 2606 OID 18125)
-- Name: barangay_services_transactionlog barangay_services_tr_user_id_e5b3c450_fk_users_use; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.barangay_services_transactionlog
    ADD CONSTRAINT barangay_services_tr_user_id_e5b3c450_fk_users_use FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6049 (class 2606 OID 17645)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6050 (class 2606 OID 17650)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6051 (class 2606 OID 17955)
-- Name: gis_mapping_disasterpronearea gis_mapping_disaster_barangay_ref_id_640f4d9d_fk_residents; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gis_mapping_disasterpronearea
    ADD CONSTRAINT gis_mapping_disaster_barangay_ref_id_640f4d9d_fk_residents FOREIGN KEY (barangay_ref_id) REFERENCES public.residents_barangay(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6069 (class 2606 OID 17975)
-- Name: gis_mapping_evacuationsite gis_mapping_evacuati_barangay_id_80a79c0e_fk_residents; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gis_mapping_evacuationsite
    ADD CONSTRAINT gis_mapping_evacuati_barangay_id_80a79c0e_fk_residents FOREIGN KEY (barangay_id) REFERENCES public.residents_barangay(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6052 (class 2606 OID 17950)
-- Name: gis_mapping_infrastructure gis_mapping_infrastr_barangay_ref_id_cbc084cc_fk_residents; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gis_mapping_infrastructure
    ADD CONSTRAINT gis_mapping_infrastr_barangay_ref_id_cbc084cc_fk_residents FOREIGN KEY (barangay_ref_id) REFERENCES public.residents_barangay(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6060 (class 2606 OID 17920)
-- Name: residents_announcement residents_announceme_barangay_id_5e44ef0b_fk_residents; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.residents_announcement
    ADD CONSTRAINT residents_announceme_barangay_id_5e44ef0b_fk_residents FOREIGN KEY (barangay_id) REFERENCES public.residents_barangay(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6061 (class 2606 OID 17781)
-- Name: residents_announcement residents_announcement_created_by_id_67fd57a8_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.residents_announcement
    ADD CONSTRAINT residents_announcement_created_by_id_67fd57a8_fk_users_user_id FOREIGN KEY (created_by_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6063 (class 2606 OID 17915)
-- Name: residents_barangay residents_barangay_admin_user_id_94b30f2c_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.residents_barangay
    ADD CONSTRAINT residents_barangay_admin_user_id_94b30f2c_fk_users_user_id FOREIGN KEY (admin_user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6059 (class 2606 OID 17775)
-- Name: residents_barangayservice residents_barangayse_resident_id_676a549f_fk_residents; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.residents_barangayservice
    ADD CONSTRAINT residents_barangayse_resident_id_676a549f_fk_residents FOREIGN KEY (resident_id) REFERENCES public.residents_resident(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6053 (class 2606 OID 17907)
-- Name: residents_household residents_household_barangay_id_62e2893c_fk_residents; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.residents_household
    ADD CONSTRAINT residents_household_barangay_id_62e2893c_fk_residents FOREIGN KEY (barangay_id) REFERENCES public.residents_barangay(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6066 (class 2606 OID 17926)
-- Name: residents_incidentreport residents_incidentre_barangay_id_5e7fcc56_fk_residents; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.residents_incidentreport
    ADD CONSTRAINT residents_incidentre_barangay_id_5e7fcc56_fk_residents FOREIGN KEY (barangay_id) REFERENCES public.residents_barangay(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6067 (class 2606 OID 17931)
-- Name: residents_incidentreport residents_incidentre_resident_id_28d08bfe_fk_residents; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.residents_incidentreport
    ADD CONSTRAINT residents_incidentre_resident_id_28d08bfe_fk_residents FOREIGN KEY (resident_id) REFERENCES public.residents_resident(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6068 (class 2606 OID 17943)
-- Name: residents_notification residents_notification_user_id_7ca23f13_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.residents_notification
    ADD CONSTRAINT residents_notification_user_id_7ca23f13_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6064 (class 2606 OID 17938)
-- Name: residents_official residents_official_barangay_id_6e4ca7b5_fk_residents; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.residents_official
    ADD CONSTRAINT residents_official_barangay_id_6e4ca7b5_fk_residents FOREIGN KEY (barangay_id) REFERENCES public.residents_barangay(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6054 (class 2606 OID 17830)
-- Name: residents_resident residents_resident_barangay_id_105459be_fk_residents; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.residents_resident
    ADD CONSTRAINT residents_resident_barangay_id_105459be_fk_residents FOREIGN KEY (barangay_id) REFERENCES public.residents_barangay(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6055 (class 2606 OID 18032)
-- Name: residents_resident residents_resident_father_id_0c75768e_fk_residents_resident_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.residents_resident
    ADD CONSTRAINT residents_resident_father_id_0c75768e_fk_residents_resident_id FOREIGN KEY (father_id) REFERENCES public.residents_resident(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6056 (class 2606 OID 17804)
-- Name: residents_resident residents_resident_household_id_3fa81f6b_fk_residents; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.residents_resident
    ADD CONSTRAINT residents_resident_household_id_3fa81f6b_fk_residents FOREIGN KEY (household_id) REFERENCES public.residents_household(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6057 (class 2606 OID 18041)
-- Name: residents_resident residents_resident_mother_id_c566864b_fk_residents_resident_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.residents_resident
    ADD CONSTRAINT residents_resident_mother_id_c566864b_fk_residents_resident_id FOREIGN KEY (mother_id) REFERENCES public.residents_resident(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6058 (class 2606 OID 17740)
-- Name: residents_resident residents_resident_user_id_e30b911d_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.residents_resident
    ADD CONSTRAINT residents_resident_user_id_e30b911d_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6062 (class 2606 OID 17798)
-- Name: residents_residentdocument residents_residentdo_resident_id_bab15a4d_fk_residents; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.residents_residentdocument
    ADD CONSTRAINT residents_residentdo_resident_id_bab15a4d_fk_residents FOREIGN KEY (resident_id) REFERENCES public.residents_resident(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6065 (class 2606 OID 17894)
-- Name: residents_service residents_service_barangay_id_81006aa7_fk_residents_barangay_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.residents_service
    ADD CONSTRAINT residents_service_barangay_id_81006aa7_fk_residents_barangay_id FOREIGN KEY (barangay_id) REFERENCES public.residents_barangay(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6070 (class 2606 OID 17997)
-- Name: residents_servicerequest residents_servicereq_barangay_id_3f1326ff_fk_residents; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.residents_servicerequest
    ADD CONSTRAINT residents_servicereq_barangay_id_3f1326ff_fk_residents FOREIGN KEY (barangay_id) REFERENCES public.residents_barangay(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6071 (class 2606 OID 18002)
-- Name: residents_servicerequest residents_servicereq_resident_id_fbfa067a_fk_residents; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.residents_servicerequest
    ADD CONSTRAINT residents_servicereq_resident_id_fbfa067a_fk_residents FOREIGN KEY (resident_id) REFERENCES public.residents_resident(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6072 (class 2606 OID 18007)
-- Name: residents_servicerequest residents_servicereq_service_id_ee36fef6_fk_residents; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.residents_servicerequest
    ADD CONSTRAINT residents_servicereq_service_id_ee36fef6_fk_residents FOREIGN KEY (service_id) REFERENCES public.residents_service(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6045 (class 2606 OID 17609)
-- Name: users_user_groups users_user_groups_group_id_9afc8d0e_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_group_id_9afc8d0e_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6046 (class 2606 OID 17604)
-- Name: users_user_groups users_user_groups_user_id_5f6f5a90_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_groups
    ADD CONSTRAINT users_user_groups_user_id_5f6f5a90_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6047 (class 2606 OID 17623)
-- Name: users_user_user_permissions users_user_user_perm_permission_id_0b93982e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_perm_permission_id_0b93982e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6048 (class 2606 OID 17618)
-- Name: users_user_user_permissions users_user_user_permissions_user_id_20aca447_fk_users_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users_user_user_permissions
    ADD CONSTRAINT users_user_user_permissions_user_id_20aca447_fk_users_user_id FOREIGN KEY (user_id) REFERENCES public.users_user(id) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2026-05-01 13:02:48

--
-- PostgreSQL database dump complete
--

\unrestrict Ogcpp37LHZ5mZCI8m43oufdXdmkgnOyxtea81HVH5lUWF2uMH9Wm7leiWXXmTNc

