# Generated by Django 4.2.29 on 2026-03-31 10:46

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterProneArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('FLOOD', 'Flood Prone'), ('LANDSLIDE', 'Landslide Prone'), ('STORM_SURGE', 'Storm Surge')], max_length=50)),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('risk_level', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')])),
            ],
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('HEALTH_CENTER', 'Health Center'), ('SCHOOL', 'School'), ('ROAD', 'Road'), ('BARANGAY_HALL', 'Barangay Hall'), ('OTHER', 'Other')], max_length=50)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('barangay', models.CharField(max_length=100)),
            ],
        ),
    ]
