# Generated by Django 4.2.29 on 2026-04-04 23:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gis_mapping', '0002_barangay_links_and_evacuation_sites'),
    ]

    operations = [
    ]
