# Generated by Django 4.2.29 on 2026-04-22 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_mapping', '0002_disasterpronearea_barangay_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructure',
            name='barangay',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
