# Generated by Django 4.2.29 on 2026-04-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0016_servicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='age_range',
            field=models.CharField(blank=True, choices=[('INFANT', 'Infant (0-1)'), ('TODDLER', 'Toddler (2-4)'), ('CHILD', 'Child (5-12)'), ('TEEN', 'Teen (13-19)'), ('ADULT', 'Adult (20-59)'), ('SENIOR', 'Senior (60+)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='birthplace',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='citizenship',
            field=models.CharField(default='Filipino', max_length=100),
        ),
        migrations.AddField(
            model_name='resident',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('WIDOWED', 'Widowed'), ('SEPARATED', 'Separated'), ('DIVORCED', 'Divorced')], max_length=20),
        ),
        migrations.AddField(
            model_name='resident',
            name='college',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='educational_attainment',
            field=models.CharField(blank=True, choices=[('NONE', 'No Formal Education'), ('ELEMENTARY_UNDERGRAD', 'Elementary Undergraduate'), ('ELEMENTARY_GRAD', 'Elementary Graduate'), ('HIGHSCHOOL_UNDERGRAD', 'High School Undergraduate'), ('HIGHSCHOOL_GRAD', 'High School Graduate'), ('VOCATIONAL', 'Vocational Course'), ('COLLEGE_UNDERGRAD', 'College Undergraduate'), ('COLLEGE_GRAD', 'College Graduate'), ('POST_GRAD', 'Post Graduate')], max_length=100),
        ),
        migrations.AddField(
            model_name='resident',
            name='elementary_school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='employment_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('EMPLOYED', 'Employed'), ('UNEMPLOYED', 'Unemployed')], max_length=20),
        ),
        migrations.AddField(
            model_name='resident',
            name='high_school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='profile_status',
            field=models.CharField(choices=[('INCOMPLETE', 'Incomplete'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved')], default='INCOMPLETE', max_length=20),
        ),
        migrations.AddField(
            model_name='resident',
            name='religion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='residency_status',
            field=models.CharField(blank=True, choices=[('PERMANENT', 'Permanent'), ('TRANSIENT', 'Transient')], max_length=50),
        ),
        migrations.AddField(
            model_name='resident',
            name='resident_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='zone_street_purok',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
