# Generated by Django 4.2.29 on 2026-04-26 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0017_resident_age_range_resident_birthplace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_from_father', to='residents.resident'),
        ),
        migrations.AddField(
            model_name='resident',
            name='father_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='has_children',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='is_present_address_same_as_permanent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_from_mother', to='residents.resident'),
        ),
        migrations.AddField(
            model_name='resident',
            name='mother_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='present_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='residency_type',
            field=models.CharField(choices=[('HOUSE_OWNER', 'House Owner'), ('BOARDER', 'Boarder'), ('TRANSIENT', 'Transient')], default='HOUSE_OWNER', max_length=20),
        ),
        migrations.AddField(
            model_name='resident',
            name='years_in_barangay',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
