# Generated by Django 4.2.29 on 2026-04-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0018_resident_father_resident_father_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='children_details',
            field=models.TextField(blank=True, help_text='Names and ages of children, especially those of legal age.', null=True),
        ),
    ]
