# Generated by Django 4.2.29 on 2026-04-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0019_resident_children_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
