# Generated by Django 4.2.29 on 2026-04-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0020_resident_permanent_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='resident_photos/'),
        ),
    ]
