# Generated by Django 4.2.29 on 2026-04-26 12:34

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0021_resident_is_verified_resident_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='boundary',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
