# Generated by Django 4.2.29 on 2026-04-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0022_barangay_boundary'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='num_children',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
