# Generated by Django 4.2.29 on 2026-04-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0023_resident_num_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='elementary_graduated_at',
            field=models.CharField(blank=True, help_text='School where elementary was completed', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='high_school_graduated_at',
            field=models.CharField(blank=True, help_text='School where high school was completed', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='student_level',
            field=models.CharField(blank=True, choices=[('ELEMENTARY', 'Elementary'), ('HIGHSCHOOL', 'High School'), ('COLLEGE', 'College')], max_length=20, null=True),
        ),
    ]
