# Generated by Django 4.2.30 on 2026-04-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0024_resident_elementary_graduated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='is_father_deceased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='is_mother_deceased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resident',
            name='mother_maiden_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='age_range',
            field=models.CharField(blank=True, choices=[('INFANT', 'Infant (0-1)'), ('CHILDHOOD', 'Childhood (2-12)'), ('ADOLESCENCE', 'Adolescence (13-17)'), ('YOUNG_ADULTHOOD', 'Young Adulthood (18-30)'), ('ADULTHOOD', 'Adulthood (31-45)'), ('MIDDLE_AGE', 'Middle Age (46-59)'), ('OLD_AGE', 'Old Age (60-74)'), ('SENIOR_CITIZEN', 'Senior Citizen (75+)')], max_length=20, null=True),
        ),
    ]
