# Generated by Django 4.2.29 on 2026-04-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0025_resident_is_father_deceased_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('WIDOWED', 'Widowed'), ('SEPARATED', 'Separated'), ('DIVORCED', 'Divorced'), ('LIVE_IN', 'Live-in')], max_length=20),
        ),
    ]
