# Generated by Django 4.2.29 on 2026-04-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0026_resident_spouse_name_alter_resident_civil_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='end_date',
            field=models.DateField(blank=True, help_text='When the announcement disappears', null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='start_date',
            field=models.DateField(blank=True, help_text='When the announcement becomes visible', null=True),
        ),
    ]
