# Generated by Django 4.2.29 on 2026-04-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0027_announcement_end_date_announcement_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
