# Generated by Django 4.2.29 on 2026-04-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0028_barangay_is_active_resident_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
