# Generated by Django 4.2.30 on 2026-05-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0029_barangay_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='away_duration_months',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resident',
            name='away_duration_years',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resident',
            name='current_location',
            field=models.CharField(blank=True, choices=[('IN_BARANGAY', 'Currently living in the barangay'), ('AWAY', 'Currently away from home')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='employment_status_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('EMPLOYED', 'Employed'), ('UNEMPLOYED', 'Unemployed'), ('RETIRED', 'Retired'), ('SELF_EMPLOYED', 'Self-employed'), ('OFW', 'OFW'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
